Product.create(:name =>'hello',:image => 'http://www.mansion-hyoka.com/arch_images/arch24_img02.jpg',:price => 10000)
Product.create(:name =>'hello',:image => 'http://www.mansion-hyoka.com/arch_images/arch24_img02.jpg',:price => 10000)
Product.create(:name =>'hello',:image => 'http://www.mansion-hyoka.com/arch_images/arch24_img02.jpg',:price => 10000)
Product.create(:name =>'hello',:image => 'http://www.mansion-hyoka.com/arch_images/arch24_img02.jpg',:price => 10000)
Product.create(:name =>'hello',:image => 'http://www.mansion-hyoka.com/arch_images/arch24_img02.jpg',:price => 10000)
Product.create(:name =>'hello',:image => 'http://www.mansion-hyoka.com/arch_images/arch24_img02.jpg',:price => 10000)
Product.create(:name =>'hello',:image => 'http://www.mansion-hyoka.com/arch_images/arch24_img02.jpg',:price => 10000)
Product.create(:name =>'hello',:image => 'http://www.mansion-hyoka.com/arch_images/arch24_img02.jpg',:price => 10000)
Product.create(:name =>'hello',:image => 'http://www.mansion-hyoka.com/arch_images/arch24_img02.jpg',:price => 10000)
Product.create(:name =>'hello',:image => 'http://www.mansion-hyoka.com/arch_images/arch24_img02.jpg',:price => 10000)
Product.create(:name =>'hello',:image => 'http://www.mansion-hyoka.com/arch_images/arch24_img02.jpg',:price => 10000)
Product.create(:name =>'hello',:image => 'http://www.mansion-hyoka.com/arch_images/arch24_img02.jpg',:price => 10000)

City.create(:name => '北海道', :roman =>'hokkaido')
City.create(:name => '青森県', :roman =>'aomori')
City.create(:name => '岩手県', :roman =>'iwate')
City.create(:name => '宮城県', :roman =>'miyagi')
City.create(:name => '秋田県', :roman =>'akita')
City.create(:name => '山形県', :roman =>'yamagata')
City.create(:name => '福島県', :roman =>'hukusima')
City.create(:name => '茨城県', :roman =>'ibaraki')
City.create(:name => '栃木県', :roman =>'totigi')
City.create(:name => '群馬県', :roman =>'gunma')
City.create(:name => '埼玉県', :roman =>'saitama')
City.create(:name => '千葉県', :roman =>'tiba')
City.create(:name => '東京都', :roman =>'tokyo')
City.create(:name => '神奈川県', :roman =>'kanagawa')
City.create(:name => '新潟県', :roman =>'nigata')
City.create(:name => '富山県', :roman =>'toyama')
City.create(:name => '石川県', :roman =>'isikawa')
City.create(:name => '福井県', :roman =>'hukui')
City.create(:name => '山梨県', :roman =>'yamanashi')
City.create(:name => '長野県', :roman =>'nagano')
City.create(:name => '岐阜県', :roman =>'gifu')
City.create(:name => '静岡県', :roman =>'sizuoka')
City.create(:name => '愛知県', :roman =>'aichi')
City.create(:name => '三重県', :roman =>'mie')
City.create(:name => '滋賀県', :roman =>'shiga')
City.create(:name => '京都府', :roman =>'kyoto')
City.create(:name => '大阪府', :roman =>'osaka')
City.create(:name => '兵庫県', :roman =>'hyogo')
City.create(:name => '奈良県', :roman =>'nara')
City.create(:name => '和歌山県', :roman =>'wakayama')
City.create(:name => '鳥取県', :roman =>'tottori')
City.create(:name => '島根県', :roman =>'shimane')
City.create(:name => '岡山県', :roman =>'okayama')
City.create(:name => '広島県', :roman =>'hiroshima')
City.create(:name => '山口県', :roman =>'yamaguchi')
City.create(:name => '徳島県', :roman =>'tokushima')
City.create(:name => '香川県', :roman =>'kagawa')
City.create(:name => '愛媛県', :roman =>'ehime')
City.create(:name => '高知県', :roman =>'kouchi')
City.create(:name => '福岡県', :roman =>'hukuoka')
City.create(:name => '佐賀県', :roman =>'saga')
City.create(:name => '長崎県', :roman =>'nagasaki')
City.create(:name => '熊本県', :roman =>'kumamoto')
City.create(:name => '大分県', :roman =>'oita')
City.create(:name => '宮崎県', :roman =>'miyazaki')
City.create(:name => '鹿児島県', :roman =>'kagoshima')
City.create(:name => '沖縄県', :roman =>'okinawa')


Boxsize.create(:boxsize =>'small' ,:name =>'小')
Boxsize.create(:boxsize =>'middle',:name =>'中')
Boxsize.create(:boxsize =>'large' ,:name =>'大')

Chara.create(:chara => 'sanrio' ,:name => 'サンリオ')
Chara.create(:chara => 'pokemon',:name => 'ポケモン')

Color.create(:color => 'white', :name => '白色')
Color.create(:color => 'pink' , :name => 'ピンク')
Color.create(:color => 'blue' , :name => '青')

Scene.create(:scene => 'marriage' ,:name => '結婚式')
Scene.create(:scene => 'birthday' ,:name => '誕生日')
Scene.create(:scene => 'employment' ,:name => '就職祝い')
Scene.create(:scene => 'birth' ,:name => '出産祝い')

AdminUser.create(:name => 'impact',:email => 'impact1234@example.com',:password => 'impact1234')

